/* Every route from SPLIT_PLAN.md §3, plus one synthetic sanitizer probe. */
export const ROUTES = [
  ["home",                "/"],
  ["programim",           "/programim"],
  ["siguria",             "/siguria"],
  ["trajnime",            "/trajnime"],
  ["trajnime-detail-rich","/trajnime/ethical-hacking-training"],
  ["trajnime-detail-min", "/trajnime/dizajn-grafik-me-ai"],
  ["forma",               "/forma/aplikim-studime-profesionale"],
  ["biznese",             "/biznese"],
  ["biznese-trajnime",    "/biznese/trajnime"],
  ["biznese-talente",     "/biznese/talente"],
  ["biznese-bursa",       "/biznese/bursa"],
  ["biznese-klasa",       "/biznese/klasa"],
  ["projektet",           "/projektet"],
  ["proj-skill-factory",  "/projektet/skill-factory"],
  ["proj-usaid",          "/projektet/usaid"],
  ["proj-sdc",            "/projektet/sdc"],
  ["proj-wow",            "/projektet/wow"],
  ["proj-kode",           "/projektet/kode"],
  ["proj-rcf",            "/projektet/rcf"],
  ["proj-luxdev",         "/projektet/luxdev"],
  ["proj-vic",            "/projektet/vic"],
  ["lajme",               "/lajme"],
  ["lajme-detail-rich",   "/lajme/cacttus-education-test"],
  ["lajme-detail-links",  "/lajme/njoftim-smoke-test-msdtk9g9"],
  ["lajme-probe",         "/lajme/sanitizer-probe"],
  ["kontakti",            "/kontakti"],
  ["rreth-nesh",          "/rreth-nesh"],
  ["ekipi",               "/ekipi"],
  ["ligjerueit",          "/ligj\u00ebrueit"],
  ["catchall",            "/kjo-rruge-nuk-ekziston"],
];
export const VIEWPORTS = [["375", 375, 812], ["1280", 1280, 800]];
